on:
  push:
    branches:
      - master

name: Main
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install ArgoCD
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd
      - name: ðŸš€ Deploy WebSocket for MyTeslaMate
        run: argocd app actions run websocket restart --kind Deployment --server ${{ secrets.ARGOCD_URL }} --auth-token ${{ secrets.ARGOCD_TOKEN }}
